# Generated by Django 2.2.3 on 2020-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200104_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Id',
            field=models.IntegerField(default=0),
        ),
    ]
