# Generated by Django 2.2.3 on 2020-01-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=500)),
                ('phone', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
