# Generated by Django 2.2.3 on 2020-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_Id', models.AutoField(primary_key=True, serialize=False)),
                ('order_Id', models.IntegerField(default='')),
                ('updae_desc', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
