# Generated by Django 2.2.3 on 2020-01-22 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_Id',
        ),
    ]
